.macro UNREGISTER_PROCESS
  lda   ORIX_CURRENT_PROCESS_FOREGROUND
  beq   @skip_UNREGISTER_PROCESS
  jsr   _orix_unregister_process
@skip_UNREGISTER_PROCESS:
.endmacro

.macro UNREGISTER_PROCESS_BY_PID_IN_ACCUMULATOR
  beq @skip_UNREGISTER_PROCESS
  jsr _orix_unregister_process
@skip_UNREGISTER_PROCESS:
.endmacro

.macro REGISTER_PROCESS str_name_process 
    lda #<str_name_process
    ldy #>str_name_process
    jsr _orix_register_process  
.endmacro
